/* Bilingual content. Every text field is { pt, en }. */
window.PORTFOLIO = {
  ui: {
    pt: {
      skip: 'Pular para os projetos',
      'nav.projects': 'Projetos', 'nav.experience': 'Experiência', 'nav.skills': 'Habilidades', 'nav.contact': 'Contato',
      'hero.eyebrow': 'Senior Software Engineer · Jundiaí, SP · Remoto',
      'hero.lead': 'Construo backends escaláveis em Go e Node.js, com AWS, Kubernetes e mensageria — e gosto de levar o produto até a tela, seja em React, Flutter ou um jogo.',
      'hero.cta': 'Ver projetos',
      'stats.years': '7+ anos', 'stats.yearsLabel': 'em tecnologia',
      'stats.go': '5+ anos', 'stats.goLabel': 'com Go em produção',
      'stats.domains': 'Fintech', 'stats.domainsLabel': 'crédito, pagamentos, banking',
      'stats.goal': 'Principal', 'stats.goalLabel': 'Engineer é o próximo passo',
      'about.eyebrow': 'Sobre', 'about.title': 'Do jogo indie ao core bancário',
      'about.p1': 'Comecei em jogos (Unity, Unreal Engine e rigging 3D), passei por QA e migrei para engenharia de software em 2021. Desde então trabalho em fintechs e produtos financeiros: integrações bancárias e Pix, enriquecimento de dados de clientes, análise de crédito e risco, gestão de investimentos via API.',
      'about.p2': 'Gosto de refatorar sistemas legados complexos, cuidar de migrações críticas sem downtime, escrever documentação que as pessoas realmente usam e alinhar o que o time constrói ao que o cliente precisa. Meus projetos pessoais são o laboratório onde testo stacks completas, do banco ao pixel.',
      'projects.eyebrow': 'Projetos', 'projects.title': 'Coisas que construí de ponta a ponta',
      'projects.sub': 'Aplicações reais, rodando localmente no momento das capturas. Cada card mostra a stack, as decisões de arquitetura e o estado atual.',
      'experience.eyebrow': 'Experiência', 'experience.title': 'Trajetória profissional',
      'skills.eyebrow': 'Habilidades', 'skills.title': 'Stack e ferramentas',
      'education.eyebrow': 'Formação', 'education.title': 'Educação',
      'languages.eyebrow': 'Idiomas', 'languages.title': 'Idiomas', 'goals.eyebrow': 'Objetivos',
      'contact.eyebrow': 'Contato', 'contact.title': 'Vamos conversar?',
      'contact.sub': 'Aberto a oportunidades sênior/principal em backend, plataformas e produtos financeiros — remoto ou híbrido em São Paulo.',
      'footer.built': 'HTML, CSS e JS puros · hospedado no GitHub Pages',
      'labels.live': 'Ver online', 'labels.repo': 'Repositório', 'labels.private': 'código privado · disponível sob pedido',
      'labels.status.live': 'em produção', 'labels.status.wip': 'em desenvolvimento', 'labels.status.done': 'concluído', 'labels.status.discontinued': 'descontinuado',
      'labels.current': 'atual', 'labels.stack': 'Stack',
    },
    en: {
      skip: 'Skip to projects',
      'nav.projects': 'Projects', 'nav.experience': 'Experience', 'nav.skills': 'Skills', 'nav.contact': 'Contact',
      'hero.eyebrow': 'Senior Software Engineer · Jundiaí, SP, Brazil · Remote',
      'hero.lead': 'I build scalable backends in Go and Node.js on AWS, Kubernetes and message brokers — and I like taking the product all the way to the screen, whether in React, Flutter or a game.',
      'hero.cta': 'See projects',
      'stats.years': '7+ years', 'stats.yearsLabel': 'in tech',
      'stats.go': '5+ years', 'stats.goLabel': 'shipping Go to production',
      'stats.domains': 'Fintech', 'stats.domainsLabel': 'credit, payments, banking',
      'stats.goal': 'Principal', 'stats.goalLabel': 'Engineer is the next step',
      'about.eyebrow': 'About', 'about.title': 'From indie games to banking cores',
      'about.p1': 'I started in games (Unity, Unreal Engine and 3D rigging), moved through QA and switched to software engineering in 2021. Since then I have worked on fintech and financial products: bank integrations and Pix instant payments, customer data enrichment, credit and risk analysis, API-first investment management.',
      'about.p2': 'I enjoy refactoring complex legacy systems, running critical migrations with zero downtime, writing documentation people actually read, and keeping what the team builds aligned with what customers need. Side projects are my lab for full-stack experiments, from database to pixel.',
      'projects.eyebrow': 'Projects', 'projects.title': 'Things I built end to end',
      'projects.sub': 'Real applications, running locally when the screenshots were taken. Each card shows the stack, the architecture decisions and the current state.',
      'experience.eyebrow': 'Experience', 'experience.title': 'Career path',
      'skills.eyebrow': 'Skills', 'skills.title': 'Stack and tooling',
      'education.eyebrow': 'Education', 'education.title': 'Education',
      'languages.eyebrow': 'Languages', 'languages.title': 'Languages', 'goals.eyebrow': 'Goals',
      'contact.eyebrow': 'Contact', 'contact.title': "Let's talk",
      'contact.sub': 'Open to senior/principal roles in backend, platform and financial products — remote or hybrid in São Paulo.',
      'footer.built': 'Plain HTML, CSS and JS · hosted on GitHub Pages',
      'labels.live': 'Live site', 'labels.repo': 'Repository', 'labels.private': 'private code · available on request',
      'labels.status.live': 'in production', 'labels.status.wip': 'in progress', 'labels.status.done': 'completed', 'labels.status.discontinued': 'discontinued',
      'labels.current': 'present', 'labels.stack': 'Stack',
    },
  },

  projects: [
    {
      id: 'karenclementeatelie',
      name: 'Karen Clemente Ateliê',
      status: 'wip',
      repo: 'https://github.com/pedroegerland/karenclementeatelie',
      repoPrivate: true,
      tags: ['Go 1.27', 'net/http', 'React 18', 'TypeScript', 'Vite', 'Tailwind', 'DynamoDB', 'S3 + CloudFront', 'AWS Lambda', 'AWS CDK (Go)', 'Docker', 'GitHub Actions'],
      shots: [
        { src: 'assets/projects/atelie_home.jpg', alt: { pt: 'Home do catálogo com hero e grade de produtos', en: 'Catalog home with hero and product grid' } },
        { src: 'assets/projects/atelie_produto.jpg', alt: { pt: 'Página de produto com specs, galeria e CTA de WhatsApp', en: 'Product page with specs, gallery and WhatsApp CTA' } },
        { src: 'assets/projects/atelie_busca.jpg', alt: { pt: 'Busca com sinônimos: "backpack" encontra mochila', en: 'Synonym search: "backpack" finds the mochila' } },
        { src: 'assets/projects/atelie_mobile_home.jpg', alt: { pt: 'Versão mobile da home', en: 'Mobile home' } },
        { src: 'assets/projects/atelie_mobile_produto.jpg', alt: { pt: 'Versão mobile do produto', en: 'Mobile product page' } },
        { src: 'assets/projects/atelie_404.jpg', alt: { pt: 'Página 404 com a identidade do ateliê', en: '404 page in the atelier identity' } },
      ],
      desc: {
        pt: 'Catálogo online de um ateliê de peças feitas à mão e personalizadas (bolsas, necessaires, mochilas). Reescrito de Flutter para um monólito Go + React: um único binário serve a API JSON e o frontend compilado.',
        en: 'Online catalog for a handmade, made-to-order atelier (bags, pouches, backpacks). Rewritten from Flutter into a Go + React monolith: one binary serves the JSON API and the compiled frontend.',
      },
      points: {
        pt: [
          'Backend Go 1.27 hexagonal lendo o catálogo do DynamoDB, com cache em memória e refresh em segundo plano (serve dado antigo se o banco falhar); imagens em S3 atrás do CloudFront.',
          'Open Graph injetado no servidor por produto, sitemap.xml e robots.txt gerados do catálogo — links no WhatsApp mostram a foto da peça.',
          'Busca sem acento e com sinônimos, slugs com compatibilidade para links antigos, produtos relacionados.',
          'Design inspirado na página Rover Pack (Dribbble); testes Go com ~85% de cobertura nos pacotes de lógica; a mesma imagem distroless roda na Lambda (Lambda Web Adapter) atrás do CloudFront, tudo em CDK Go com deploy por OIDC.',
        ],
        en: [
          'Hexagonal Go backend reading the catalog from DynamoDB, with in-memory cache and background refresh (serves stale data if the database is down); images on S3 behind CloudFront.',
          'Server-injected Open Graph per product plus sitemap.xml and robots.txt generated from the catalog — WhatsApp links preview the piece photo.',
          'Accent-insensitive synonym search, slugs backwards-compatible with old links, related products.',
          'Design inspired by the Rover Pack product page (Dribbble); Go tests at ~85% coverage on logic packages; the same distroless image runs on Lambda (Lambda Web Adapter) behind CloudFront, all in Go CDK with OIDC deploys.',
        ],
      },
    },
    {
      id: 'imobiliaria',
      name: 'Imobiliária Marques & Henriques',
      status: 'discontinued',
      repo: 'https://github.com/pedroegerland/imobiliaria-marques-e-henriques',
      repoPrivate: true,
      tags: ['React 18', 'TypeScript', 'Tailwind', 'Vite', 'Go 1.27', 'AWS Lambda', 'API Gateway', 'DynamoDB', 'Cognito', 'S3', 'AWS SAM', 'Vercel'],
      shots: [
        { src: 'assets/projects/imob_home.jpg', alt: { pt: 'Home com busca por modalidade, tipo e localização', en: 'Home with search by deal type, property type and location' } },
        { src: 'assets/projects/imob_imoveis.jpg', alt: { pt: 'Listagem com filtros laterais (dados de demonstração)', en: 'Listing with sidebar filters (demo data)' } },
        { src: 'assets/projects/imob_detalhe.jpg', alt: { pt: 'Detalhe do imóvel com carrossel e contato do corretor', en: 'Property detail with carousel and realtor contact' } },
        { src: 'assets/projects/imob_imoveis_aluguel.jpg', alt: { pt: 'Filtro de locação aplicado', en: 'Rent filter applied' } },
        { src: 'assets/projects/imob_home_destaques.jpg', alt: { pt: 'Imóveis em destaque na home', en: 'Featured listings on the home page' } },
        { src: 'assets/projects/imob_login.jpg', alt: { pt: 'Login do painel do corretor (Cognito)', en: 'Realtor dashboard login (Cognito)' } },
        { src: 'assets/projects/imob_mobile_imoveis.jpg', alt: { pt: 'Listagem no celular', en: 'Mobile listing' } },
        { src: 'assets/projects/imob_mobile_detalhe.jpg', alt: { pt: 'Detalhe no celular', en: 'Mobile detail' } },
      ],
      desc: {
        pt: 'Site imobiliário completo com área pública e painel do corretor, construído em AWS Serverless. Dezessete Lambdas em Go cobrem imóveis, upload de fotos via URL pré-assinada, aprovação de usuários e sincronização de dados do corretor.',
        en: 'Full real-estate website with a public area and a realtor dashboard, built on AWS Serverless. Seventeen Go Lambdas cover listings, presigned-URL photo uploads, user approval and realtor data sync.',
      },
      points: {
        pt: [
          'Backend Go em camadas (domain / usecase / adapter) com DynamoDB, S3 e validação de JWT do Cognito; infraestrutura como código com AWS SAM.',
          'Fluxo de cadastro com aprovação de corretor por admin, triggers de Cognito (pre-auth, post-confirmation, custom message) e reset de senha.',
          'Frontend React com favoritos, carrossel de fotos, contato por WhatsApp/telefone/e-mail e painel para criar, editar e desativar imóveis.',
          'Deploy contínuo: SAM para o backend com outputs publicados no SSM, Vercel (migração planejada para Amplify) para o frontend.',
          'Capturas feitas com o frontend real apontando para uma API local com imóveis de demonstração (o ambiente de dev estava sem anúncios).',
        ],
        en: [
          'Layered Go backend (domain / usecase / adapter) with DynamoDB, S3 and Cognito JWT validation; infrastructure as code with AWS SAM.',
          'Sign-up flow with admin approval of realtors, Cognito triggers (pre-auth, post-confirmation, custom message) and password reset.',
          'React frontend with favorites, photo carousel, WhatsApp/phone/e-mail contact and a dashboard to create, edit and deactivate listings.',
          'Continuous deploy: SAM for the backend with outputs published to SSM, Vercel (Amplify migration planned) for the frontend.',
          'Screenshots use the real frontend against a local API serving demo listings (the dev environment had no properties yet).',
        ],
      },
    },
    {
      id: 'lunchtab',
      name: 'Lunchtab',
      status: 'wip',
      repo: 'https://github.com/pedroegerland/lunchtab',
      repoPrivate: true,
      tags: ['Go 1.27', 'net/http', 'SQLite (pure Go)', 'JWT HS256', 'bcrypt', 'React 18', 'TypeScript', 'Vite', 'Tailwind', 'TanStack Query', 'Docker', 'GitHub Actions'],
      shots: [
        { src: 'assets/projects/cg_dashboard.jpg', alt: { pt: 'Painel do dia: vendas, solicitações pendentes com aprovar/cancelar, mais vendidos e saldo baixo', en: 'Day dashboard: sales, pending requests with approve/cancel, top sellers and low balances' } },
        { src: 'assets/projects/cg_comanda_apos_compra.jpg', alt: { pt: 'Comanda do aluno com extrato imutável: compras, crédito e solicitação pendente', en: 'Student tab with immutable ledger: purchases, credit and a pending request' } },
        { src: 'assets/projects/cg_compra_modal.jpg', alt: { pt: 'Registrar compra no caixa com validação de saldo', en: 'Counter sale with balance validation' } },
        { src: 'assets/projects/cg_cardapio.jpg', alt: { pt: 'Cardápio por categoria com disponibilidade', en: 'Menu by category with availability toggles' } },
        { src: 'assets/projects/cg_comandas_filtro.jpg', alt: { pt: 'Comandas filtradas por turma (perfil cantina)', en: 'Tabs filtered by class (canteen role)' } },
        { src: 'assets/projects/cg_estudantes.jpg', alt: { pt: 'Estudantes e vínculo com responsáveis', en: 'Students and guardian links' } },
        { src: 'assets/projects/cg_usuarios.jpg', alt: { pt: 'Usuários com papéis e senha temporária', en: 'Users with roles and temporary passwords' } },
        { src: 'assets/projects/cg_meus_alunos.jpg', alt: { pt: 'Visão do responsável: meus alunos', en: 'Guardian view: my students' } },
        { src: 'assets/projects/cg_login.jpg', alt: { pt: 'Login', en: 'Login' } },
        { src: 'assets/projects/cg_mobile_aluno.jpg', alt: { pt: 'Comanda no celular (responsável)', en: 'Student tab on mobile (guardian)' } },
        { src: 'assets/projects/cg_mobile_solicitar.jpg', alt: { pt: 'Solicitar item no celular', en: 'Request an item on mobile' } },
      ],
      desc: {
        pt: 'Gestão de cantinas escolares: cardápio, comanda por aluno, crédito dos responsáveis e pedidos antecipados, com perfis de escola, cantina e responsável. Reescrito de Flutter + Firebase para um monólito Go + React com banco embutido.',
        en: 'School-cafeteria management: menu, per-student tab, guardian top-ups and pre-orders, with admin, canteen and guardian roles. Rewritten from Flutter + Firebase into a Go + React monolith with an embedded database.',
      },
      points: {
        pt: [
          'Backend Go 1.27 só com stdlib + SQLite puro Go (sem CGO): arquitetura hexagonal, portas para repositórios/hasher/tokens, migrações embarcadas, dinheiro em centavos.',
          'Autenticação própria: JWT HS256 implementado com crypto/hmac, bcrypt, senha temporária com troca obrigatória; autorização por papel e por vínculo responsável→aluno.',
          'Comanda com extrato imutável (saldo antes/depois, autor, status); compra recusada por inteiro se o saldo não cobre; solicitação só debita na aprovação da cantina.',
          'Frontend React + TanStack Query com painel do dia, caixa com carrinho, filtros de comanda, gestão de usuários/escolas; testes Go de caso de uso e HTTP (73–79% nos pacotes de lógica); Dockerfile distroless.',
        ],
        en: [
          'Go 1.27 backend on stdlib + pure-Go SQLite (no CGO): hexagonal layout, ports for repositories/hasher/tokens, embedded migrations, money in integer cents.',
          'Own auth: HS256 JWT built on crypto/hmac, bcrypt, temporary passwords with forced change; authorization by role and by guardian→student link.',
          'Tab with immutable ledger (balance before/after, actor, status); a sale is refused whole when the balance cannot cover it; requests only debit when the canteen approves.',
          'React + TanStack Query frontend with day dashboard, counter cart, tab filters, user/school management; Go use-case and HTTP tests (73–79% on logic packages); distroless Dockerfile.',
        ],
      },
    },
    {
      id: 'aegiskids',
      name: 'AegisKids',
      status: 'wip',
      tags: ['Go 1.27', 'chi', 'AWS Lambda', 'DynamoDB single-table', 'Cognito', 'API Gateway WebSocket', 'AWS CDK (Go)', 'React Native', 'Expo', 'TypeScript', 'Kotlin', 'Swift', 'pnpm workspaces'],
      shots: [
        { src: 'assets/projects/wmk_api_flow.jpg', fit: 'contain', alt: { pt: 'API real rodando local com DynamoDB Local: família, pareamento, dispositivo, localização, tempo de tela e bloqueio', en: 'Real API running locally on DynamoDB Local: family, pairing, device, location, screen time and block' } },
        { src: 'assets/projects/wmk_tests.jpg', fit: 'contain', alt: { pt: 'Saída real dos testes Go do backend e estrutura do monorepo', en: 'Real Go backend test output and monorepo layout' } },
      ],
      desc: {
        pt: 'AegisKids: plataforma de controle parental em que pais acompanham localização, uso de apps e tempo de tela, aprovam instalações, bloqueiam o aparelho remotamente e pedem uma captura de tela com consentimento da criança.',
        en: 'AegisKids: parental-control platform where parents follow location, app usage and screen time, approve installs, lock the device remotely and request a screenshot with the child’s consent.',
      },
      points: {
        pt: [
          'Monorepo pnpm com apps React Native separados para pais e filhos, pacotes compartilhados de tipos e cliente HTTP.',
          'Backend Go hexagonal (domain → app → infra/transport) rodando em Lambda + API Gateway, DynamoDB single-table com GSI e testes de domínio/casos de uso com fakes.',
          'Módulos nativos: Kotlin (Device Admin, Accessibility, UsageStats, MediaProjection) e Swift (Family Controls, DeviceActivityMonitor).',
          'Canal realtime por API Gateway WebSocket (sem FCM/Firebase: o app do filho mantém o socket pelo foreground service) e infra com AWS CDK em Go (auth, dados, realtime, API). Sem UI capturável ainda — as imagens mostram a API respondendo de verdade sobre DynamoDB Local e a suíte de testes.',
        ],
        en: [
          'pnpm monorepo with separate React Native apps for parents and children plus shared type and HTTP client packages.',
          'Hexagonal Go backend (domain → app → infra/transport) on Lambda + API Gateway, DynamoDB single-table with a GSI, and domain/use-case tests with fakes.',
          'Native modules: Kotlin (Device Admin, Accessibility, UsageStats, MediaProjection) and Swift (Family Controls, DeviceActivityMonitor).',
          'Realtime channel over API Gateway WebSocket (no FCM/Firebase: the child app holds the socket from its foreground service) and infrastructure with AWS CDK in Go (auth, data, realtime, API). No capturable UI yet — the images show the API answering for real on DynamoDB Local and the test suite.',
        ],
      },
    },
  ],

  experience: [
    { role: { pt: 'Senior Software Engineer', en: 'Senior Software Engineer' }, company: { pt: 'Fintech (confidencial)', en: 'Fintech (confidential)' }, location: { pt: 'Remoto', en: 'Remote' }, start: '2024-12', end: null,
      stack: 'Node.js · TypeScript · AWS Serverless · Lambda · Step Functions · SQS/SNS · PostgreSQL · Redis · Docker',
      points: { pt: ['Enriquecimento de dados para onboarding de clientes e integrações que automatizam rotinas de ERPs de terceiros.', 'Soluções de análise de crédito, pagamentos e transações com dados integrados de comerciantes.', 'Migrações e atualizações críticas com foco em continuidade; documentação de APIs, guias e diagramas de arquitetura.'],
                en: ['Data enrichment for customer onboarding and integrations automating third-party ERP routines.', 'Credit analysis, payments and transaction solutions built on integrated merchant data.', 'Critical updates and migrations focused on continuity; API docs, user guides and architecture diagrams.'] } },
    { role: { pt: 'Senior Software Engineer', en: 'Senior Software Engineer' }, company: { pt: 'Trio', en: 'Trio' }, location: { pt: 'Remoto', en: 'Remote' }, start: '2025-04', end: '2025-12',
      stack: 'Go · GraphQL · PostgreSQL · AWS · Terraform · Kubernetes · Docker',
      points: { pt: ['Segunda passagem, no mesmo produto: soluções digitais de gestão patrimonial para cliente norte-americano do setor de aposentadoria.', 'Evolução das APIs que permitem a instituições financeiras lançar experiências de investimento personalizáveis, com foco em segurança, time to market e menor CAPEX.'],
                en: ['Second stint on the same product: digital wealth-management solutions for a US client in the retirement sector.', 'Evolved the APIs that let financial institutions launch customizable investment experiences, focusing on security, time to market and lower CAPEX.'] } },
    { role: { pt: 'Senior Software Engineer', en: 'Senior Software Engineer' }, company: { pt: 'Trio', en: 'Trio' }, location: { pt: 'Jundiaí, SP', en: 'Jundiaí, Brazil' }, start: '2024-11', end: '2025-01',
      stack: 'Go · GraphQL · PostgreSQL · AWS · Terraform · Kubernetes · Docker',
      points: { pt: ['Soluções digitais de gestão patrimonial para cliente norte-americano do setor de aposentadoria.', 'Produtos oferecidos via API para que instituições financeiras lancem experiências de investimento personalizáveis com rápida implementação e menor CAPEX.'],
                en: ['Digital wealth-management solutions for a US client in the retirement sector.', 'API-delivered products letting financial institutions launch customizable investment experiences with fast time to market and lower CAPEX.'] } },
    { role: { pt: 'Sr Software Engineer — Go', en: 'Sr Software Engineer — Go' }, company: { pt: 'Traive', en: 'Traive' }, location: { pt: 'Brasil', en: 'Brazil' }, start: '2023-01', end: '2024-11',
      stack: 'Go · GraphQL · Kafka · PostgreSQL · Redis · S3 · Kubernetes · Terraform · Datadog · React',
      points: { pt: ['Soluções em Go para crédito agro e avaliação de risco, garantindo scores para pedidos de fundos de crédito.', 'Enriquecimento e integração de produtos com clientes; operação das aplicações na AWS com Kubernetes e Terraform.', 'Manutenção e novas funcionalidades no frontend React; priorização guiada por feedback de usuários e métricas.'],
                en: ['Go solutions for agri credit and risk assessment, producing scores for credit-fund requests.', 'Product enrichment and client integrations; ran the applications on AWS with Kubernetes and Terraform.', 'Maintained and extended the React frontend; prioritized work from user feedback and system metrics.'] } },
    { role: { pt: 'Senior Software Engineer — Go', en: 'Senior Software Engineer — Go' }, company: { pt: 'Dock', en: 'Dock' }, location: { pt: 'Brasil', en: 'Brazil' }, start: '2022-06', end: '2022-12',
      stack: 'Go · GraphQL · PostgreSQL · RabbitMQ · Redis · S3 · Kubernetes · Terraform · Datadog',
      points: { pt: ['Qualidade de código, pipelines e refatoração de projetos complexos, unificando duplicações entre times.', 'Ferramentas de acompanhamento de desempenho e mecanismos de atualização; migrações críticas com downtime mínimo.'],
                en: ['Code quality, pipelines and refactoring of complex projects, unifying duplication across teams.', 'Performance-tracking tooling and update mechanisms; critical migrations with minimal downtime.'] } },
    { role: { pt: 'Software Engineer Pleno — Go', en: 'Mid-level Software Engineer — Go' }, company: { pt: 'Zak', en: 'Zak' }, location: { pt: 'São Paulo', en: 'São Paulo' }, start: '2021-11', end: '2022-06',
      stack: 'Go · PostgreSQL · MongoDB · Redis · Kafka · Kubernetes · Terraform · Datadog',
      points: { pt: ['Refatoração de projetos legados complexos e simplificação de arquitetura para operações eficientes.', 'Consolidação de meios de pagamento e payloads aos padrões da empresa.'],
                en: ['Refactored complex legacy projects and streamlined the architecture for efficient operations.', 'Consolidated payment methods and payloads to company standards.'] } },
    { role: { pt: 'Software Engineer (Jr → Pleno) — Node.js / Go', en: 'Software Engineer (Junior → Mid) — Node.js / Go' }, company: { pt: 'Stefanini', en: 'Stefanini' }, location: { pt: 'São Paulo', en: 'São Paulo' }, start: '2021-02', end: '2021-10',
      stack: 'Node.js · TypeScript · Go · Kafka · DynamoDB · ElasticSearch · Serverless · Docker',
      points: { pt: ['Operações bancárias: recargas, transações por celular e pagamentos via Pix; integrações com Banco Topázio, Votorantim e ABC.', 'Enriquecimento de dados de clientes e integração com bureau (PH3A SOAP) sobre o core bancário Topaz; reconciliação com o Banco BV.'],
                en: ['Banking operations: top-ups, mobile transactions and Pix payments; integrations with Topázio, Votorantim and ABC banks.', 'Customer data enrichment and bureau integration (PH3A SOAP) on the Topaz banking core; reconciliation with BV bank.'] } },
    { role: { pt: 'Freelance Golang Developer', en: 'Freelance Golang Developer' }, company: { pt: 'Confidencial', en: 'Confidential' }, location: { pt: 'São Paulo', en: 'São Paulo' }, start: '2021-05', end: '2021-06',
      stack: 'Go · Docker',
      points: { pt: ['APIs, mudanças de framework, correção de bugs e revisões de código.'], en: ['APIs, framework changes, bug fixes and code reviews.'] } },
    { role: { pt: 'QA Engineer', en: 'QA Engineer' }, company: { pt: 'Stefanini', en: 'Stefanini' }, location: { pt: 'São Paulo', en: 'São Paulo' }, start: '2020-05', end: '2021-02',
      stack: 'Appium · Node.js · Postman · Axios · AWS Lambda · CloudWatch',
      points: { pt: ['Testes manuais e automatizados de apps React Native; massas de teste via automações REST; monitoramento e alarmes na AWS.'], en: ['Manual and automated testing of React Native apps; REST-driven test data; AWS monitoring and alarms.'] } },
    { role: { pt: 'QA Engineer', en: 'QA Engineer' }, company: { pt: 'MarketUP', en: 'MarketUP' }, location: { pt: 'São Paulo', en: 'São Paulo' }, start: '2019-06', end: '2020-04',
      stack: 'Selenium WebDriver JS · OrangeTesting · BDD/TDD · JavaScript · jQuery',
      points: { pt: ['Automação de testes para avaliar qualidade e desempenho dos sistemas da empresa.'], en: ['Test automation to assess quality and performance of company systems.'] } },
    { role: { pt: 'Freelance Game Developer', en: 'Freelance Game Developer' }, company: { pt: 'Freelance', en: 'Freelance' }, location: { pt: 'São Paulo', en: 'São Paulo' }, start: '2016-12', end: '2019-06',
      stack: 'Unity · C# · Unreal Engine 4 · Blueprint/C++ · Rigging',
      points: { pt: ['Inventários, menus, sistema de vida, respawn e IA de inimigos; adaptação de jogos para mobile mantendo desempenho.'], en: ['Inventories, menus, health system, respawn and enemy tracking; adapted games to mobile while keeping performance.'] } },
  ],

  skills: [
    { title: { pt: 'Backend', en: 'Backend' }, items: ['Go', 'Node.js', 'TypeScript', 'GraphQL', 'REST / Swagger', 'gRPC', 'Arquitetura hexagonal'] },
    { title: { pt: 'Cloud & Infra', en: 'Cloud & Infra' }, items: ['AWS (Lambda, SQS/SNS, Step Functions, DynamoDB, S3, Cognito)', 'Kubernetes', 'Docker', 'Terraform', 'AWS CDK / SAM', 'Serverless', 'Datadog', 'GitHub Actions'] },
    { title: { pt: 'Dados & Mensageria', en: 'Data & Messaging' }, items: ['PostgreSQL', 'MongoDB', 'DynamoDB', 'Redis', 'Kafka', 'RabbitMQ', 'ElasticSearch', 'Firestore'] },
    { title: { pt: 'Frontend & Mobile', en: 'Frontend & Mobile' }, items: ['React', 'Tailwind CSS', 'Vite', 'Flutter', 'React Native / Expo', 'Kotlin & Swift (módulos nativos)'] },
    { title: { pt: 'Games & 3D', en: 'Games & 3D' }, items: ['Unreal Engine (C++ / Blueprint)', 'Unity (C#)', 'Rigging de personagens'] },
    { title: { pt: 'Práticas', en: 'Practices' }, items: ['Refatoração de legado', 'Migrações sem downtime', 'Testes (unit, httptest, fakes)', 'Documentação técnica', 'Code review', 'Trabalho com produto'] },
  ],

  education: [
    { title: { pt: 'Tecnólogo em Análise e Desenvolvimento de Sistemas', en: 'Associate Degree in Systems Analysis and Development' }, school: 'Universidade Anhembi Morumbi (Laureate)', year: '2022' },
    { title: { pt: 'Programação para Unreal Engine 4', en: 'Game Programming for Unreal Engine 4' }, school: 'Axis — Escola de Arte e Efeitos Visuais', year: '2018' },
    { title: { pt: 'Personagem 3D', en: '3D Character' }, school: 'Axis — Escola de Arte e Efeitos Visuais', year: '2019' },
  ],

  languages: [
    { name: { pt: 'Português', en: 'Portuguese' }, level: { pt: 'Nativo', en: 'Native' } },
    { name: { pt: 'Inglês', en: 'English' }, level: { pt: 'Avançado (C1)', en: 'Advanced (C1)' } },
    { name: { pt: 'Espanhol', en: 'Spanish' }, level: { pt: 'Básico (A1)', en: 'Beginner (A1)' } },
  ],

  goals: {
    pt: ['Tornar-me Principal Engineer', 'Ajudar times e empresas a prosperar com engenharia sólida'],
    en: ['Become a Principal Engineer', 'Help teams and companies thrive through solid engineering'],
  },
};
